### ISSUE TITLE
Add URL Support in Terminal

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/url-title-preview#6]
It would be beneficial to add support for URLs in the terminal. This would allow users to review the URL on the terminal before opening it, improving the overall user experience and efficiency.

**Comment by chaim-chv** [comment]
The [`registerHoverProvider`](https://code.visualstudio.com/api/references/vscode-api#languages.registerHoverProvider) method is only applicable to text documents in the editor.
The VS Code API does not currently support hover providers in the terminal.

**Comment by baruchiro** [comment]
Can you give us a reference?

The closest one I found is the [`window.registerTerminalLinkProvider`](https://code.visualstudio.com/api/references/vscode-api#window.registerTerminalLinkProvider).

Closing for now, thank you!

**Comment by chaim-chv** [comment]
> Can you give us a reference?

In the docs, you can see that this method applies to `DocumentSelector`, which you need to provide. However, `DocumentSelector` doesn't include anything that's not text documents in the editor.

> The closest one I found is the [`window.registerTerminalLinkProvider`](https://code.visualstudio.com/api/references/vscode-api#window.registerTerminalLinkProvider).

That method can actually work, but it looks like the only customizable part of the hover popup is the text. Therefore, we won't be able to show the cover image, etc.
