### ISSUE TITLE
Add meta content to the Hover

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/url-title-preview#8]
The [`HoverProvider`](https://code.visualstudio.com/api/references/vscode-api#HoverProvider) supports Markdown.

Please read the Meta Tags from the destination URL (you can use tools like https://www.opengraph.xyz/) and show a full card inside the hover (including an image).

**Comment by jacobra19** [comment]
@baruchiro 
sure thing, are the latest changes published already?

**Comment by baruchiro** [comment]
Yes, `v0.0.4`

**Comment by jacobra19** [comment]
@baruchiro #9 🙏
